haproxy_exporter.go

Remove deprecated flag, it's been 5 months.

Allow exporting of haproxy's process stats

---

haproxy_exporter.go

NewProcessCollectorPIDFn interface has changed and requires a separate
error message now.
@juliusv @brian-brazil

Adjust haproxy process collector initialization

---

haproxy_exporter.go

Make flag names consistent across projects.

---

Dockerfile

This fixes the broken docker build

Install gcc in Dockerfile

---

README.md

fixing in correct docker run example

fixing in correct docker run example in readme.md

---

haproxy_exporter.go

Depends on https://github.com/prometheus/log/pull/3

Migrate logging to prometheus/log.

---

README.md

@discordianfish @juliusv @brian-brazil

Fix haproxy.scrape-uri in README.md

---

haproxy_exporter.go
haproxy_exporter_test.go

Handles instance MAINT status as down. Fixes #35.
@iwinux @juliusv @brian-brazil

Fix status field parsing

---

haproxy_exporter.go

The graceful error handling added in v0.5.1 introduced a new error case
where an exporter got stuck in an endless loop when hitting an
unexpected non-parser error. This change ensures that only
csv.ParseErrors get handled gracefully.
Can't read CSV: read tcp 127.0.0.1:30270->127.0.0.1:5000: i/o timeout
@juliusv @brian-brazil 
I tried to write a test for that, but I wasn't able to. Any I/O timeout was already handled during the HTTP Get() method.

Limit graceful CSV error handling to parse errors

---

haproxy_exporter.go

This does not add any benefit, but removes a potential error case where
the deadline is already started by scrape() while the exporter waits for
the lock.
---
Have this lying around for some time, it's a first improvement at least. I'll continue with the rewrite of the exporter next weekend.
@juliusv @fabxc

Remove channel and goroutines

---

AUTHORS.md

Remove Julius from maintainers, add Tobi

---

haproxy_exporter.go

convert collected metrics from milliseconds to seconds
I took back the open PR #84 in order to finish it since it is in WIP for a long time; I added the original author in the signed-off-by tags.
closes #83 
closes #84
cc @grobie

Fix wrong values in HTTP request duration metrics

---

README.md

Change as per #117
Signed-off-by: Daniel Foster <merlin83b@users.noreply.github.com>

Update README for Kingpin boolean setting

---

.travis.yml
Makefile
Makefile.common
haproxy_exporter.go
haproxy_exporter_test.go

Use Makefile.common from Prometheus

---

.circleci/config.yml
.promu.yml
go.mod
vendor/modules.txt

Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>

Bump go version to 1.14

---

haproxy_exporter.go
test/server_broken_csv.metrics
test/server_without_checks.metrics
test/unix_domain.metrics

Add client/server abort counters

---

Makefile

The CircleCI test job runs `make` without any arguments by default. This
change adds a new default make target and includes `vet` and
`checkmetrics`. All test metrics files are checked individually.
Note: The current promtool installation target doesn't ensure the
newesst version is used.

Enforce go vet and promtool check metrics

---

README.md

readme: fix doc regarding boolean option for no ssl verify

---

README.md
go.mod
go.sum
haproxy_exporter.go

Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>

Add TLS and basic authentication

---

README.md

Update README to mention new USE_PROMEX make flag for HAProxy.

Update README to mention new USE_PROMEX make flag for HAProxy.

---

README.md

Image update in readme
