.gitignore, Makefile, Makefile.COMMON
This is a test-drive for separating all common build functionality into
a separate Makefile.COMMON, which is included from an individual
project's Makefile (mainly for the various exporters, which should have
almost identical Makefiles, modulo accrued inconsistencies).
The main Makefile then only needs to define the VERSION and TARGET
variables and the Makefile.COMMON defines all the common targets. While
doing this, I decided per variable which one should be simply expanded
(`:=`) vs. conditionally set (`?=`). The former allows evaluating values
only once and on the spot (good for potentially costly evaluations),
while the latter allows overriding variables from the parent Makefile.
Unfortunately it's not possible to combine the two variants (like
`?:=`), so I had to chose which one …
=> Extract common Makefile parts into Makefile.COMMON.

haproxy_exporter.go
The requests error (ereq, 12th field) in [CSV format][1] is a metric only
available in frontend and listen objects.
[1]: https://cbonte.github.io/haproxy-dconv/configuration-1.5.html#9.1
=> ereq (requests errors) is a frontend metric

Dockerfile, Makefile.COMMON
Following the docker related PR series.
New Dockerfile using the [alpine-golang-make-onbuild](https://github.com/sdurrheimer/alpine-golang-make-onbuild) base image whose goal is to unified the way to dockerize prometheus tools and exporters based on Golang.
The binary is build using make. (Golang is installed via make too, respecting the GO_VERSION).
A testable image is available under my name on Docker hub : [Link](https://registry.hub.docker.com/u/sdurrheimer/haproxy-exporter/)
As always, the [alpine-golang-make-onbuild](https://github.com/sdurrheimer/alpine-golang-make-onbuild)  image can be also move under Prometheus organization.
@juliusv @discordianfish
=> New Dockerfile using alpine-golang-make-onbuild base image

Makefile.COMMON, haproxy_exporter.go, haproxy_exporter_test.go
So far -haproxy.server-metrics-fields only allowed to disable all but
one server metrics. With this change it's possible to completely disable
all server metrics.
@brian-brazil @discordianfish @juliusv
=> Disable server metrics

haproxy_exporter.go
=> Add current_queue metric for servers

haproxy_exporter.go, haproxy_exporter_test.go
Haproxy versions <1.6.4 respond with invalid CSV lines when a server
got drained via an agent[0]. This caused the haproxy_exporter to stop
reporting any metrics for following metrics.
[0]: http://permalink.gmane.org/gmane.comp.web.haproxy/27011
Fixes #45.
@matthiasr @bitfehler
=> Handle invalid CSV lines gracefully

README.md
To reduce confusion (cf. #49), make it clear that this is supported and
how to use it.
@brian-brazil @grobie
=> Add `-scrape.uri` examples to README

haproxy_exporter.go, haproxy_exporter_test.go
As these are only collected if explicitly enabled anyways, I figured there'd be
no harm in exposing those.
@grobie
=> Add chkfail and downtime server metrics.

README.md, haproxy_exporter.go, haproxy_exporter_test.go
Support for HAProxy's stats socket as described in http://cbonte.github.io/haproxy-dconv/configuration-1.6.html#stats%20socket
It is enabled by using 'unix:/your/file' as the scape URI.
This saves setting up the HTTP admin website, and makes haproxy_exporter potentially easier to use with nbproc>1
=> support for 'stats' unix socket

haproxy_exporter.go
With net.Conn.SetDeadline the connection could not be reused for
additional requests after the timeout, and even a fast response could
time out while reading, because the timer was started by a previous
request.
With a five second scrape interval, the log will fill up with this
error:
ERRO[0108] Unexpected error while reading CSV: read tcp n.n.n.n:57648->m.m.m.m:443: i/o timeout source=haproxy_exporter.go:331
With this change I can not see any more errors and by using netstat I
can see that the same port/connection is reused for a while.
I used 5 seconds for testing, and I guess it's not often used in production, but I think having keepalive working is worth fixing.  See also:
https://golang.org/pkg/net/http/#Client
https://medium.com/@nate510/don-t-use-go-s-default-http-client-4804cb19f77 …
=> Fix timeout and keepalive by using Client.Timeout

haproxy_exporter.go, haproxy_exporter_test.go
While the former way seems to work as intended, the behavior is at best
undocumented.
@beorn7
=> Use a proper type assertion when checking for csv.ParseError

haproxy_exporter.go, haproxy_exporter_test.go
@brian-brazil  ... this pull request adds column 6, ("slim [LFBS]:") which contains the session limit for each individual server. 
The value can be used i.e. to compare to the number of currently active connections, so it is very much of interest and not just a to some extend "static" piece of configuration.
=> Add column 6 ("slim [LFBS]: configured session limit") to serverMetrics

README.md, haproxy_exporter.go
Fixes #70.
```
Usage of ./haproxy_exporter:
-haproxy.pid-file string
Path to HAProxy pid file.
If provided, the standard process metrics get exported for the HAProxy
process, prefixed with 'haproxy_process_...'. The haproxy_process exporter
needs to have read access to files owned by the HAProxy process. Depends on
the availability of /proc.
https://prometheus.io/docs/instrumenting/writing_clientlibs/#process-metrics.
-haproxy.scrape-uri string
URI on which to scrape HAProxy. (default "http://localhost/;csv")
...
```
@JensRantil
=> Improve help text of -haproxy.pid-file flag

haproxy_exporter.go
haproxy 1.7 introduces a distinction between connection and sessions,
sessions represents an end to end connection:
"with the introduction of SSL, proxy protocol and layer4 ACLs it was
needed to cut the end-to-end sessions in smaller parts, hence the
introduction of 'connections'"
this patch renames the old `connections_total` to `sessions_total` in order
to use the same vocabulary as haproxy; I was puzzled to keep the compatibility
but in the long term I think this will introduces more incomprehension
than it resolves.
so this is a breaking change.
`connections_total` now represents the new metric from haproxy.
also add comment to the new available metrics.
=> support conn_tot stats

README.md, haproxy_exporter.go, haproxy_exporter_test.go
In one of my projects haproxy_exporter is located on a different machine and should be able to communicate via HTTPS with certificate verification disabled.
Here is the pull request that solves the problem.
This pull request addresses Issue #74.
=> HTTPS support with insecure verify option

haproxy_exporter.go
for now, only exporting current number of active servers
not exporting "number of backup servers" since I did not found quickly what was the meaning of "backend servers" since the numbers on 1.8 I have are strictly identical to active servers.
cc @grobie
=> export current number of active servers

go.mod, haproxy_exporter.go, haproxy_exporter_test.go, test/deadline.metrics, test/invalid_config.metrics, test/not_found.metrics, test/older_haproxy_versions.metrics, test/server_broken_csv.metrics, test/server_without_checks.metrics, test/unix_domain.metrics, test/unix_domain_deadline.metrics, test/unix_domain_not_found.metrics, vendor/github.com/prometheus/client_golang/prometheus/testutil/testutil.go, vendor/modules.txt
This also required completely re-doing the tests using the excellent
CollectAndCompare() from the new client_golang, which uncovered a bug in
HAProxy exporter when scraping old HAProxy versions that did not have all CSV
fields (some metrics would be randomly missing in the output because we broke
out of a loop in a non-deterministic way).
Fixes #43
Signed-off-by: Julius Volz <julius.volz@gmail.com>
=> Convert HAProxy Exporter to using const metrics

README.md
As of `2.0.0` (released yesterday), HAProxy includes an official Prometheus endpoint in it's source that can be built into your binaries with a `make` flag and can be configured from your `haproxy.cfg` file.
This PR documents such module as solicited in #150.
=> Documented 2.0.0's official Prometheus exporter module

haproxy_exporter.go, haproxy_exporter_test.go, test/deadline.metrics, test/invalid_config.metrics, test/not_found.metrics, test/older_haproxy_versions.metrics, test/server_broken_csv.metrics, test/server_without_checks.metrics, test/unix_domain.metrics, test/unix_domain_deadline.metrics, test/unix_domain_not_found.metrics
Add a new haproxy_version_info metric by running the "show info" command
on the UNIX socket.
This feature is not supported in HTTP mode. It will require some
refactoring of the HTTP stats method to handle this.
Signed-off-by: Ben Kochie <superq@gmail.com>
=> Add support for "show info"

haproxy_exporter.go, haproxy_exporter_test.go, test/deadline.metrics, test/invalid_config.metrics, test/not_found.metrics, test/older_haproxy_versions.metrics, test/server_broken_csv.metrics, test/server_without_checks.metrics, test/unix_domain.metrics, test/unix_domain_deadline.metrics, test/unix_domain_not_found.metrics
* Add support for counter metrics.
* Update metrics to correct types.
* Fix metric naming conventions for exporter countermetrics.
Fixes: https://github.com/prometheus/haproxy_exporter/issues/30
Signed-off-by: Ben Kochie <superq@gmail.com>
=> Fix metric types

haproxy_exporter.go, haproxy_exporter_test.go
Allow excluding metrics for server slots depending on their status. Using
this you can avoid reporting metrics for unused server slots when using
dynamic scaling in haproxy.
E.g. you can use
--haproxy.server-exclude-states='DOWN,MAINT,MAINT (resolution)'
=> Add filtering on server status

haproxy_exporter.go, test/server_broken_csv.metrics
According to Prometheus best practices, metrics should be using base
units. Times should be exported in seconds, the check duration metric is
the only outlier here.
With this change, all tested metrics adhere to the guidelines:
for file in test/*.metrics; do
promtool check metrics < $file
done
=> Use seconds in haproxy_check_duration_seconds as unit

haproxy_exporter.go
To properly check which version of the exporter had been installed from
a binary it helps a lot to support the --version flag as the other
exporters. It's just a one-line fix to print the version information on
the CLI.
```
$ ./haproxy_exporter --version
haproxy_exporter, version 0.11.0 (branch: master, revision: 166e9ba36bfcd70f433a5665064c08ba0b9937df)
build user:       tboerger@osiris.local
build date:       20200721-09
```
=> Add version flag

haproxy_exporter.go
haproxy_server_http_connect_time_average_seconds
haproxy_server_http_total_time_average_seconds
haproxy_server_http_queue_time_average_seconds
haproxy_server_http_response_time_average_seconds
Added the above metrics, these are reported by haproxy, but exporter doesn't collect them. They're important identifying outliers at a quick glance in larger pools.
=> Added missing _time_average_seconds per server metrics

README.md, haproxy_exporter.go, haproxy_exporter_test.go
I need to run the `haproxy_exporter` from an environment which can only reach the target haproxy stats API by going through an HTTP proxy. The way `haproxy_exporter` currently executes its GET requests (with a customized `http.Transport` to allow disabling TLS validation) ignores the proxy settings defined in the traditional environment variables (`$HTTP(S)_PROXY`, `$NO_PROXY`).  This PR fixes that, by adding the proxy from [`http.ProxyFromEnvironment`](https://pkg.go.dev/net/http#ProxyFromEnvironment) to the `http.Transport`. If there is no proxy env vars, or the target haproxy domain is in `$NO_PROXY`, the proxy will be `nil`, and nothing changes in the way requests are executed.
It can be tested, for instance, by running a local [mitmproxy](https://mitmproxy.org/) service, and running …
=> enable optional use of an HTTP proxy

haproxy_exporter.go
Hello,
A very simple PR to add support for `tcp` scheme. It is identical with `unix` (same haproxy API endpoint, not the same as http UI) except you access it by tcp address. We use it by default for a long time.
Here is an example how to enable it this way:
```
global
stats socket ipv4@127.0.0.1:9899 level admin
```
Thanks!
=> Support tcp scheme

haproxy_exporter_test.go
`ioutil` is deprecated from go1.16 (ref: https://go.dev/doc/go1.16#ioutil).
So removed them.
Signed-off-by: inosato <si17_21@yahoo.co.jp>
=> Remove ioutil

README.md
Providing basic auth parameters through the command line
is insecure and raised some eyebrows in
https://github.com/prometheus/haproxy_exporter/issues/102
Kingpin in
https://github.com/alecthomas/kingpin#reading-arguments-from-a-file
provides a way to specify parameters through a file so we can
document that too.
In addition to prevent the leak of the password in the process table
(making any user currently logged on the machine able to read the
password), this also prevent a remote user to read the credentials
through the pprof cmdline service.
Signed-off-by: François Rigault <frigo@amadeus.com>
=> Document passing arguments through a file

haproxy_exporter.go, haproxy_exporter_test.go, test/unix_domain.metrics
HAProxy docs mention that the [Idle_pct](http://cbonte.github.io/haproxy-dconv/2.5/management.html#7) metric indicates how busy the event loop is; The closer to zero the value, the closer HAProxy is to its processing capacity.
This seems like a useful metric for capacity planning, so this PR is to include it metrics when scraping HAProxy via unix sockets.
=> Add idle metric

haproxy_exporter.go, test/unix_domain.metrics
The official HAProxy exporter plugin uses
`haproxy_process_idle_time_percent`, let's be consistent with that.
Follow-up for #236.
Signed-off-by: Matthias Rampke <matthias@prometheus.io>
=> Use same name for idle percent metric as upstream

haproxy_exporter.go
As of Go 1.2(!) this is always the case. Silences a linter warning.
=> Remove unnecessary TrailingComma
